version: '3'

services:
  tinkoff-invest-robot-sandbox:
    image: 'romanew/invest:sandbox-latest'
    container_name: tinkoff-invest-robot-sandbox
    network_mode: host
    environment:
      - server.port=10003
      - spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/invest-sandbox
      - spring.datasource.username=${POSTGRES_USER}
      - spring.datasource.password=${POSTGRES_PASSWORD}
      - candle.listener.enabled=true
      - tinkoff.emulator=false
      - tinkoff.is-token-sandbox=true
      - tinkoff.token=${TINKOFF_TOKEN_SANDBOX}
      - tinkoff.account-id=b0052195-ad84-4eb2-b80d-c41fffe6b78d
#      - telegram.bot.token=${TELEGRAM_BOT_TOKEN}
#      - telegram.bot.chat-id=${TELEGRAM_BOT_CHAT_ID}
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M